name: CI-SPLaSK-assessment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  initialize:
    runs-on: ubuntu-latest
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        id: Initialize-step
        with: 
          access-token: ${{secrets.ENOVADE_TOKEN}}
        
  scan-website:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Send request to scan website
        id: scan-step
        uses: Enovade/splask@v1.0.1
        with:
          splaskurl: ${{secrets.ENOVADE_TOKEN}}
          url: 'https://www.jpa.gov.my'
          scope: 'all'
          
      - name: Save result to file 
        run: echo ${{toJson(steps.scan-step.outputs.jawapan)}} > jawapan.json
        
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: jawapan.json
          if-no-files-found: error
